import type {Metadata} from "next";
import {Geist, Geist_Mono, Playfair_Display, DM_Sans} from "next/font/google";
import "./globals.css";
import {Providers} from "@/components/utils/providers/providers";


// For titles
const playdairDisplay = Playfair_Display({
    variable:"--font-playfair",
    subsets: ['latin']
})

// For Body
const dmSans =  DM_Sans({
    variable:"--font-dm-sans",
    subsets: ['latin']
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`
            ${geistSans.variable} 
            ${geistMono.variable} 
            ${playdairDisplay.variable} 
            ${dmSans.variable} 
            antialiased bg-background font-dm-sans`}
        >
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    )
}
